void maxCol(double A[nmax][mmax], double max[mmax], int n, int m);
void sigmaArray(double A[nmax][mmax], double sigma[mmax], int n, int m);
void sigmaRecalc(double A[nmax][mmax], double sigma[mmax], int index, int n, int m);
void permuta(double A[nmax][mmax], double sigma[mmax], int index,  int n, int m);
int maxIndex(double max[mmax], int k, int m);
void clean(double x[], int n);
double maximo(double x[], int n);
boolean vetorNulo(double x[], int n);
boolean normaliza(double x[], int n, int m);
double calculaMu(double x[], int n);
void produtoQA(double A[nmax][mmax], double gama, int index, int n, int m);
